import { Foods } from './shared/model/Food';
export const sample_food: Foods[] = [
    {
        id: "1",
        name: "mitom",
        price: 3,
        tags: ['xao'],
        favorite: false,
        stars: 3,
        imageUrl: 'https://static.nationalgeographic.co.uk/files/styles/image_3200/public/pcspainlondon-food-and-drink-photography-tapas-revolution-nic-crilly-hargrave-415300dpihr.jpg?w=1900&h=1257',
        origins: ["nga"],
        cookTime: 'string',
    },
    {
        id: "2",
        name: "pizza",
        price: 3,
        tags: ['xao'],
        favorite: false,
        stars: 3,
        imageUrl: 'https://cdn.shopify.com/s/files/1/2628/9270/files/mango-2400_cab7a249-532b-46db-b779-5e6fb243b63f.jpg?v=1630140424',
        origins: ["anh", 'phap'],
        cookTime: 'string',
    },
    {
        id: "3",
        name: "garan",
        price: 3,
        tags: ['chien'],
        favorite: true,
        stars: 3,
        imageUrl: 'https://d3ldzx7fxfvsfy.cloudfront.net/kraft8x/17/1654757113314_883x1501.jpg',
        origins: ["tay ban nha", 'itali'],
        cookTime: 'string',
    },
    {
        id: "4",
        name: "heoquay",
        price: 3,
        tags: ['sup'],
        favorite: false,
        stars: 3,
        imageUrl: 'https://static.nationalgeographic.co.uk/files/styles/image_3200/public/pcspainlondon-food-and-drink-photography-tapas-revolution-nic-crilly-hargrave-415300dpihr.jpg?w=1900&h=1257',
        origins: ["phap"],
        cookTime: 'string',
    },
    {
        id: "5",
        name: "thitbo",
        price: 3,
        tags: ['sup'],
        favorite: false,
        stars: 3,
        imageUrl: 'https://web-assets.bcg.com/3c/3d/794ddde7481695d246407d66e179/food-for-thought-the-untapped-climate-opportunity-in-alternative-proteins-rectangle.jpg',
        origins: ["nga"],
        cookTime: 'string',
    },
    {
        id: "3",
        name: "garan",
        price: 3,
        tags: ['nuong'],
        favorite: false,
        stars: 3,
        imageUrl: 'https://d3ldzx7fxfvsfy.cloudfront.net/kraft8x/17/1654757113314_883x1501.jpg',
        origins: ["phap"],
        cookTime: 'string',
    },
]